# NUM_OBSERVER_NODE = 1
NUM_SLAVE_NODE = 1
IP_NW = "192.168.56."

SLAVE_IP_START = 190

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos7"
  config.vm.box_check_update = false

  config.vm.define "master" do |node|
      node.vm.provider "virtualbox" do |vb|
        vb.name = "master"
        vb.memory = 4000
        vb.cpus = 2
      end
      node.vm.hostname = "master"
      node.vm.network :private_network, ip: "192.168.56.132"
      node.vm.network "forwarded_port", guest: 22, host: 26310
      node.vm.provision "setup-dns", type: "shell", :path => "update-dns.sh"
  end

  (1..NUM_SLAVE_NODE).each do |i|
    config.vm.define "worker0#{i}" do |node|
      node.vm.provider "virtualbox" do |vb|
        vb.name = "worker0#{i}"
        vb.memory = 2000
        vb.cpus = 2
      end
      node.vm.hostname = "worker0#{i}"
      node.vm.network :private_network, ip: IP_NW + "#{SLAVE_IP_START + i}"
      node.vm.network "forwarded_port", guest: 22, host: "#{2610 + i}"
      node.vm.provision "setup-dns", type: "shell", :path => "update-dns.sh"
    end
  end

  config.vm.provision "setup-deployment-user", type: "shell" do |s|
      ssh_pub_key = File.readlines("./keys/worker.pem.pub").first.strip
      s.inline = <<-SHELL
          # create deploy user
          useradd -s /bin/bash -d /home/deploy/ -m -G wheel deploy
          echo 'deploy ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
          mkdir -p /home/deploy/.ssh && chown -R deploy:deploy /home/deploy/.ssh
          echo #{ssh_pub_key} >> /home/deploy/.ssh/authorized_keys
          chown -R deploy:deploy /home/deploy/.ssh/authorized_keys
          chmod -R 0700 /home/deploy/.ssh
          chmod -R 0600 /home/deploy/.ssh/authorized_keys
          # config timezone
          timedatectl set-timezone Asia/Ho_Chi_Minh
      SHELL
  end
end